cache:
  directories:
  - "$HOME/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_866c48c033f1_key -iv $encrypted_866c48c033f1_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- tar -xzf credentials.tar.gz
- gcloud auth activate-service-account --key-file client-secret.json
script:
- gsutil rsync -d -r files gs://io-osf-staging-static
- gcloud compute url-maps invalidate-cdn-cache io-osf-staging-static --path "/preprints-assets/*"
